GHL Methods
timjedrek/pitcairn-flight pull request #5
Opened 2024-03-14 15:43 UTC by raminka13

- [x] to_ghl methods in each model.

2024-03-15 04:04 UTC, timjedrek requested changes

2024-03-15 04:04 UTC, timjedrek commented on app/models/discover_flight.rb
Need to add the note payload and map it in GHL.
===========================================
          Select aircraft category:  #{self.aircraft}
    
          Is there anything else you'd like us to know: #{self.comments}
        
          Selected Date: #{self.preferred_date}
          Selected Time: #{self.preferred_availability}
          Alternate Date: #{self.alternate_date}
          Alternate Time: #{self.alternate_availability}

2024-03-15 04:04 UTC, timjedrek commented on app/models/enrollment.rb
Same with this.. no note payload.

2024-03-15 04:04 UTC, timjedrek commented on app/models/quiz_result.rb
Same with this, no note payload.

2024-03-15 04:04 UTC, timjedrek commented on app/models/recreational_flight.rb
Same with this.. no note payload.

2024-03-15 15:12 UTC, raminka13 commented
- [x] Added the remaining fields for each form in their respective model method.

2024-03-19 08:14 UTC, timjedrek commented on app/models/checkout.rb
Let's not "resolve" the comments.  When an issue/bug is fixed just comment that it's fixed.  I like having the conversation out for notes when we look back at the code in the future.  It's good notes.

2024-03-19 08:15 UTC, timjedrek commented on app/models/discover_flight.rb
fixed

2024-03-19 08:15 UTC, timjedrek commented on app/models/enrollment.rb
payload added

2024-03-19 08:15 UTC, timjedrek commented on app/models/message.rb
line 7

2024-03-19 08:24 UTC, timjedrek commented
This is merged

2024-03-19 08:24 UTC, closed without merging